version: '2'
services:
  rest:
    image: fastapi
    ports:
        - 81:8000
    
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: fastapi
      MONGO_INITDB_ROOT_PASSWORD: fastapi

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: fastapi
      ME_CONFIG_MONGODB_ADMINPASSWORD: fastapi
      ME_CONFIG_MONGODB_URL: mongodb://fastapi:fastapi@mongo:27017/
      ME_CONFIG_BASICAUTH: false
